# Generated by Django 2.2.5 on 2019-09-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hood',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
