# Generated by Django 2.2.5 on 2019-09-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190913_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='admin',
        ),
    ]
