# Generated by Django 2.2.5 on 2019-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_hood_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='count',
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(default='location', max_length=100),
        ),
    ]
