# Generated by Django 2.2.5 on 2019-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190913_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(default='phone number', max_length=20),
        ),
    ]
